import test from 'node:test'; import assert from 'node:assert/strict';
import { filterReminders, getSummary, localDateKey, nextOccurrence, searchReminders, shouldReopenOnReschedule, validateReminder, weekRange } from '../src/reminders.js';
const base={id:'1',title:'Pagar internet',notes:'',date:'2026-08-25',time:'12:00',priority:'medium',repeat:'none',completed:false};
test('genera fecha local estable',()=>assert.equal(localDateKey(new Date(2026,7,5)),'2026-08-05'));
test('rechaza título vacío',()=>assert.equal(validateReminder({...base,title:''},new Date('2026-08-25T10:00:00')),'Escribe un título.'));
test('filtra pendientes y búsqueda',()=>{const items=[base,{...base,id:'2',title:'Comprar pan',completed:true}]; assert.deepEqual(filterReminders(items,'pending','internet').map(x=>x.id),['1']);});
test('calcula la semana de lunes a domingo',()=>assert.deepEqual(weekRange('2026-08-25'),{start:'2026-08-24',end:'2026-08-30'}));
test('resume vencidas y tareas de la semana',()=>{const items=[base,{...base,id:'2',date:'2026-08-20'},{...base,id:'3',date:'2026-08-30',completed:true},{...base,id:'4',date:'2026-09-01'},{...base,id:'5',date:'2026-08-23',completed:true}];assert.deepEqual(getSummary(items,'2026-08-25'),{pending:2,today:1,done:1,overdue:1})});
test('crea siguiente repetición semanal',()=>{const next=nextOccurrence({...base,repeat:'weekly'}); assert.equal(next.date,'2026-09-01'); assert.equal(next.completed,false);});
test('repite en días específicos',()=>{const next=nextOccurrence({...base,repeat:'custom_days',repeatDays:[1,5]});assert.equal(next.date,'2026-08-28')});
test('repite por intervalo de semanas',()=>{const next=nextOccurrence({...base,repeat:'interval',repeatInterval:2,repeatUnit:'weeks'});assert.equal(next.date,'2026-09-08')});
test('repite el último día del siguiente mes',()=>{const next=nextOccurrence({...base,date:'2026-12-31',repeat:'last_day'});assert.equal(next.date,'2027-01-31')});
test('busca tareas dentro de una semana usando fechas reales',()=>{const items=[base,{...base,id:'2',date:'2026-08-30',title:'Cierre contable'},{...base,id:'3',date:'2026-09-01'}];assert.deepEqual(searchReminders(items,{dateFrom:'2026-08-24',dateTo:'2026-08-30'}).map(x=>x.id),['1','2'])});
test('combina periodo, estado y texto',()=>{const items=[base,{...base,id:'2',title:'Cierre contable',date:'2026-08-26',completed:true},{...base,id:'3',title:'Cierre contable',date:'2026-09-02'}];assert.deepEqual(searchReminders(items,{query:'contable',dateFrom:'2026-08-24',dateTo:'2026-08-30',status:'completed'}).map(x=>x.id),['2'])});
test('reabre una tarea completada cuando se reagenda',()=>{const done={...base,completed:true};assert.equal(shouldReopenOnReschedule(done,{date:'2026-08-26'}),true);assert.equal(shouldReopenOnReschedule(done,{time:'13:00'}),true)});
test('conserva el estado al editar sin reagendar',()=>{const done={...base,completed:true};assert.equal(shouldReopenOnReschedule(done,{title:'Pagar servicio'}),false);assert.equal(shouldReopenOnReschedule(done,{date:done.date,time:done.time}),false)});
